### ISSUE TITLE
Make a PR to Mage, we'll get it merged :)

### ISSUE THREAD

**Issue by natefinch** [iwittkau/mage-select#3]
I'm still a bit wary about bash completion, but I do miss it, too :)

**Comment by iwittkau** [comment]
Ok, cool! I feel very honored.

How would you suggest integrating it into `mage`? As a separate main package with its own resulting binary or with a flag (`-i` = interactive mode)?

**Comment by sheldonhull** [comment]
@natefinch are you still interested in this great little tool to be an optional way to execute when mage is run without any args? I find it a great experience, and was getting some updates in, when I noticed this issue again. Up for a PR?

**Comment by natefinch** [comment]
So I'll admit that when I filed this, I thought it was just bash completion, and this is a little fancier than that. I'm not sure if I'm ready to take on all those dependencies in the core of Mage.
