### ISSUE TITLE
Mage 13.1 update needed to allow for running with magefiles directory

### ISSUE THREAD

**Issue by sheldonhull** [iwittkau/mage-select#5]
Without compiling for Mage 13.1 the feature for nesting magefiles in `magefiles` directory breaks the ability of `mage-select` to work.

**Comment by sheldonhull** [comment]
@iwittkau if you'd like I could contribute a `renovate.json` config that would allow it to automatically create pr's or even automerge when mage upstream gets updated. It saves me a ton of work and keeps your dependencies updated automatically or with gate for you.

**Comment by iwittkau** [comment]
`renovate` sounds like a great idea! I don't know if I can find time this week, though. Can you point me to an example?

**Comment by sheldonhull** [comment]
@iwittkau i don't mind helping there. Let me see if I can send you a PR.

**Comment by iwittkau** [comment]
As a quick fix I updated the dependency manually for now.

**Comment by sheldonhull** [comment]
@iwittkau nice! If you'll install the github app for renovate (can dcope to this repo if you want) I'll push the config. I'll configure Mage specifically to auto approve and it will be zero overhead. Any other deps can be manually reviewed or set to automerge if patch level, to further eliminate noise.  Cheers!

**Comment by iwittkau** [comment]
@sheldonhull done ✅
